name = "Assistant"
model = "gpt-4-turbo-preview"
instructions_file = "instructions.md"

[[tools]]
type = "code_interpreter"

[[tools]]
type = "retrieval"

[[tools]]
type = "function"
[tools.function]
name = "getWeather"
description = "Get the weather for a given time period and location. Return the weather naturally, as if in a conversation"
[tools.function.parameters]
type = "object"
[tools.function.parameters.properties.msg]
type = "string"
description = "A string containing location and time. For example, if user message is: 'What is the weather in London tomorrow noon?', the parameter would be 'London tomorrow noon', or PREFERABLY 'London 12:00 tomorrow'"

[[tools]]
type = "function"
[tools.function]
name = "getCalendar"
description = "Get the the users calendar events"
[tools.function.parameters]
type = "object"
[tools.function.parameters.properties.upto]
type = "string"
description = "The time range for which to get calendar events. For example, if the User message is: 'Whats my schedule like this week', upto would be '7 days'. If no time range is specified, Do not provide an input, the function defaults 'upto' to 7 days"

[[file_bundles]]
bundle_name = "source-code"
src_dir = "../src"
src_globs = ["**/*.py"]
dst_ext = "py"

[[file_bundles]]
bundle_name = "knowledge"
src_dir = "files"
src_globs = ["*.md"]
dst_ext = "md"

[[file_bundles]]
bundle_name = "memory"
src_dir = "../src"
src_globs = ["**/*.json"]
dst_ext = "json" 