name = "Assistant"
model = "gpt-4-turbo-preview"
instructions_file = "instructions.md"

[[tools]]
type = "code_interpreter"

[[tools]]
type = "retrieval"

[[tools]]
type = "function"
[tools.function]
name = "getWeather"
description = """

    This function allows you to obtain the weather when a User asks for it. The user query does not have to be direct, so it should be called even when the User asks, for example, if they should bring out an umbrella.
    
    :Params:

        msg: Optional[str]

            When calling this function, you should pass a string containing a location and a time (if provided by the user).

                Example:

                    User: 'I wonder if its going to be cloudy tomorrow at 12:00 in Amsterdam.'

                    -> getWeather('tomorrow at 12:00 Amsterdam')

            If no location or time is specified. The function will default to the User's current location and time.

                Example:

                    User: 'How's the weather?'

                    -> getWeather()

    :Returns:

        weather_report: str

            A weather report with information about the weather and user Query. Deliver it in Natural language, round the temperature to the nearest degree. Omit certain details depending on context.

                Example:

                    User: 'How's the weather?'

                    -> getWeather()

                        You should respond something similar to:
                            -> 'Today is quite sunny with a temperature of 13 degrees. Seems like a good time to take a walk.'

                Example:

                    User: 'I wonder if its going to be cloudy tomorrow at 12:00 in Amsterdam.'

                    -> getWeather('tomorrow at 12:00 Amsterdam')

                        You should respond something similar to:
                            -> 'It's going to be cloudy tomorrow noon in Amsterdam, with a temperature of 11 degrees. You should bring a coat!'
"""

[tools.function.parameters]
type = "object"
[tools.function.parameters.properties.msg]
type = "string"
description = """

    msg: Optional[str]

        When calling this function, you should pass a string containing a location and a time (if provided by the user).

            Example:

                User: 'I wonder if its going to be cloudy tomorrow at 12:00 in Amsterdam.'

                -> getWeather('tomorrow at 12:00 Amsterdam')

        If no location or time is specified. The function will default to the User's current location and time.

            Example:

                User: 'How's the weather?'

                -> getWeather()

"""

[[tools]]
type = "function"
[tools.function]
name = "getCalendar"
description = """

This function allows you to retrieve a Users calendar events. The user query does not have to be direct, so it should be called even when the User asks, for example, if they are free this evening or if they have anything planned for the weekend.
    
    :Params:

        upto: Optional[str]

            When calling this function, you should pass a string containing a time (if provided by the user). 

                Example:

                    User: 'Am I free this weekend?'

                    -> getCalendar('this weekend')

            If no time is specified. The function will default to providing the calendar events for 7 days.

                Example:

                    User: 'How's my schedule looking like?'

                    -> getCalendar()

    :Returns:

        calendar_reports: list[str]

            A calendar report with information about the Users calendar events. Deliver it in Natural language. Omit certain details depending on context.

                Example:

                    User: 'Am I free this weekend?'

                    -> getCalendar('this weekend')
                        You should respond something similar to:
                            -> This weekend you have no events scheduled. Enjoy your weekend

                            * In the calendar_reports, you will get events that pertain to the entire period between the current date of the User query, and the weekend, but any events not occuring in the weekend should be ommited, as they are not related to the User query.

                Example:

                    User: 'How's my schedule looking like?'

                    -> getCalendar()

                        -> 'This week you have 3 events: 
                                1. English exam
                                2. Dinner with Bob
                                3. Buy plane tickets
                            Seems like you have a fun week ahead, would you like me to help you prepare for any of these events?'

                            * If there are many events, avoid giving details as the response will be cluttered, instead, ask the User if they would like more details, if so, provide them, additionally, you are encouraged to assist the User for specific events, in the Above example, a good response would offer to assist with preparing for an English exam.
"""
[tools.function.parameters]
type = "object"
[tools.function.parameters.properties.upto]
type = "string"
description = """

    upto: Optional[str]

        When calling this function, you should pass a string containing a time (if provided by the user). 

            Example:

                User: 'Am I free this weekend?'

                -> getCalendar('this weekend')

        If no time is specified. The function will default to providing the calendar events for 7 days.

            Example:

                User: 'How's my schedule looking like?'

                -> getCalendar()

"""

[[tools]]
type = "function"
[tools.function]
name = "readEmail"
description = """

This function allows you to retrieve the 5 most recent emails in a User mailbox. The user query does not have to be direct.

    :Params:

        There are no parameters to pass for this function

    :Returns:

        email_reports: list[str]

            A email report with information about the Users emails. Deliver it in Natural language. Omit certain details depending on context.

                Example:

                        User: 'Do I have any new mail?'

                        -> readEmails()

                            -> 'Here are your 5 most recent messages: 
                                    1. EMAIL 1 Subject
                                    2. EMAIL 2 Subject
                                    3. EMAIL 3 Subject
                                    4. EMAIL 4 Subject
                                    5. EMAIL 5 Subject'

                                * Avoid giving details as the response will be cluttered, instead, ask the User if they would like more details, if so, provide them. If the user asks for more details about an email specifically, a good follow up message would include all information for that specific email in the email_reports.
                                
                                * Additionally, you are encouraged to assist the User for specific events in follow up messages. If a user asks for details on a specific email, offer assistance regarding the email body.

                                * If a user asks for details, you can also offer to reply to the email. If the user agrees, refer to the sendEmail function with the sender as recipient.
"""
[tools.function.parameters]
type = "object"
[tools.function.parameters.properties]

[[tools]]
type = "function"
[tools.function]
name = "writeEmail"
description = """

This function allows you to compose an email. The user query does not have to be direct.

THIS IS A PREREQUISITE FUNCTION FOR THE sendEmail FUNCTION. You should call this function before calling the sendEmail function.

    :Params:

        recipient: str

            When calling this function, you should pass a string containing the recipient of the email.

                Example:

                    User: 'Send an email to John.Doe@outlook.com'

                    -> writeEmail('John.Doe@outlook.com', 'Subject', 'Body')

        subject: str

            When calling this function, you should pass a string containing the subject of the email.

                Example:

                    User: 'Send an email to John Doe about the project'

                    -> writeEmail('John Doe', 'Action Plan for Project', 'Body')

        body: str

            When calling this function, you should pass a string containing the body of the email.

                Example:

                    User: 'Send an email to John Doe about the project, asking if he has any updates'

                    * For all emails, you should compose the body of the email in a way that is polite and professional; do not be overly verbose unless otherwise specified by the user.

                    -> writeEmail('John Doe', 'Subject', 'Body')

        attachments: Optional[list[str]]

            When calling this function, you should pass a list of strings containing the paths to the attachments of the email.

                Example:

                    User: 'Send an email to John Doe about the project, asking if he has any updates, and attach the project plan'

                    -> writeEmail('John Doe', 'Subject', 'Body', ['path/to/attachment1', 'path/to/attachment2'])

    :Returns:

        (m: O365.Message, email_reports: list[str])

            A tuple containing the email object and a confirmation message. Deliver the confirmation message in Natural language.
            Keep the mail object in memory for future reference.

                Example:

                        User: 'Write an email to John.Doe@outlook.com about the project, asking if he has any updates, and attach the project plan: project_plan.pdf'

                        -> writeEmail('John.Doe@outlook.com', 'Action Plan for Project', **Body**, [project_plan.pdf])

                            * The body parameter of the email should be composed in a way that is polite and professional unless otherwise specified by the user. Do not be overly verbose.

                            Good example:
                                Good aftenoon John,

                                I hope this message finds you well. I am writing to inquire if you have any updates on the project. I have attached the project plan for your reference.
                            
                            Bad example:

                                Hey John, I need to know if you have any updates on the project. I have attached the project plan.

                            -> message: O365.Message, email_report: list[str]

                                * Your response should look something like this:
                                    -> Your email to John.Doe@outlook.com has been composed:
                                        Subject: Action Plan for Project
                                        Body: I hope this message finds you well. I am writing to inquire if you have any updates on the project. I have attached the project plan for your reference.
                                        Attachments: project_plan.pdf
                                    
                                    Would you like to send it now?

                                    **IF THE USER AGREES TO SEND THE EMAIL, REFER TO THE sendEmail FUNCTION WITH THE MESSAGE OBJECT AS THE PARAMETER.**
"""
[tools.function.parameters]
type = "object"
[tools.function.parameters.properties.recipient]
type = "string"
description = """

    recipient: str

        When calling this function, you should pass a string containing the recipient of the email.

            Example:

                User: 'Send an email to John.Doe@outlook.com'

                -> writeEmail('Jhon.Doe@outlook.com', 'Subject', 'Body')

"""
[tools.function.parameters.properties.subject]
type = "string"
description = """

    subject: str

        When calling this function, you should pass a string containing the subject of the email.

            Example:

                User: 'Send an email to John Doe about the project'

                -> writeEmail('John Doe', 'Action Plan for Project', 'Body')

"""
[tools.function.parameters.properties.body]
type = "string"
description = """

    body: str

        When calling this function, you should pass a string containing the body of the email.

            Example:

                User: 'Send an email to John Doe about the project, asking if he has any updates'

            * For all emails, you should compose the body of the email in a way that is polite and professional; do not be overly verbose unless otherwise specified by the User.

                -> writeEmail('John Doe', 'Subject', **BODY**)

"""
[tools.function.parameters.properties.attachments]
type = "array"
description = """

    attachments: Optional[list[str]]

        When calling this function, you should pass a list of strings containing the paths to the attachments of the email.

            Example:

                User: 'Send an email to John Doe about the project, asking if he has any updates, and attach the project plan project_plan.pdf' 

                -> writeEmail('John Doe', 'Subject', 'Body', ['project_plan.pdf'])

"""
[tools.function.parameters.required]
required = ["recipient", "subject", "body"]


[[tools]]
type = "function"
[tools.function]
name = "sendEmail"
description = """

Send an email to the recipient. This function should be called after the writeEmail function AND USER CONFIRMATION.

    :Params:

        message: O365.Message

            When calling this function, you should pass the message object returned by the writeEmail function.

                Example:

                    User: 'Looks good, send the email'

                    -> sendEmail(message: O365.Message)
    
    :Returns:
    
            email_reports: list[str]
    
                A confirmation message. Deliver the confirmation message in Natural language.
    
                    Example:
    
                        User: 'Send the email'
    
                        -> sendEmail(message)
    
                            * Your response should look something like this:
                                -> 'Your email has been sent to RECIPIENT
                                    Subject: SUBJECT
                                    Body: BODY
                                    Attachments: ATTACHMENTS'
"""
[tools.function.parameters]
type = "object"
[tools.function.parameters.properties.message]
type = "object"
description = """

    message: O365.Message

        When calling this function, you should pass the message object returned by the writeEmail function.

            Example:

                User: 'Looks good, send the email'

                -> sendEmail(message: O365.Message)

"""
[tools.function.parameters.required]
required = ["message"]

[[file_bundles]]
bundle_name = "source-code"
src_dir = "../src"
src_globs = ["**/*.py"]
dst_ext = "py"

[[file_bundles]]
bundle_name = "knowledge"
src_dir = "files"
src_globs = ["*.md"]
dst_ext = "md"

[[file_bundles]]
bundle_name = "memory"
src_dir = "../src"
src_globs = ["**/*.json"]
dst_ext = "json" 