name = "Assistant"
model = "gpt-4-turbo-preview"
instructions_file = "instructions.md"

[[tools]]
type = "code_interpreter"

[[tools]]
type = "retrieval"

[[tools]]
type = "function"
[tools.function]
name = "getWeather"
description = "Get the weather for a given time period and location. Return the weather naturally, as if in a conversation"
[tools.function.parameters]
type = "object"
[tools.function.parameters.properties.msg]
type = "string"
description = "The user input message, e.g. 'What is the weather in London?' do not alter the input when passing it to the function."


[[file_bundles]]
bundle_name = "source-code"
src_dir = "../src"
src_globs = ["**/*.py"]
dst_ext = "py"

[[file_bundles]]
bundle_name = "knowledge"
src_dir = "files"
src_globs = ["*.md"]
dst_ext = "md"

[[file_bundles]]
bundle_name = "memory"
src_dir = "../src"
src_globs = ["**/*.json"]
dst_ext = "json" 